== Changelog

=== [0.2.2] - 2020-10-31

Added:

* updated badigeon sources up to 1.1
* minor bug fixes with xml parsing
* bug fix in badigeon file processing


=== [0.2.1] - 2020-08-15

Added:

* flag :overwrite-version-file to overwrite file with artifact version during bump.
It may be useful for push artifact version to ENV variable from :overwrite-version-file. 
* added distributionManagement support when generating pom

=== [0.2.0] - 2020-07-18

Added:

* support to set artifact version via ARTIFACT_VERSION environment variable

Changed:

* updated sources of badigeon up to 0.0.13

=== [0.1.11] - 2020-05-16

Fixed:

* javac messages.

=== [0.1.10] - 2020-04-18

Added:

* print javac verbose info when compiling java sources.

Fixed:

* javac expected different key from pbuild.edn. Now :java-src-folder is used.

=== [0.1.9 Next] - 2020-03-07

Changed:

* default jlink options now has "--add-modules" "java.base,java.xml,java.desktop,java.management,java.logging,java.sql"

Fixed:

* spec don't work when :omit-source? is true. Now do not delete source files in clojure.core ns

=== [0.1.8] - 2020-03-03

Changed:

* :omit-source-ns is removed cause :omit-source? option had no bug. BREAKING CHANGE between 0.1.7 only!
* now delete not only .clj, but .cljc, .java files too when :omit-source? is true

=== [0.1.7] - 2020-03-02 

Fixed:

* :omit-source? option has serious bug: deletes all source files but should delete files only inside 
current project folder. 
* added :omit-source-ns as list of top level namespaces where src files should be deleted in uberjar 
mode when :omit-source? is true.

Changed:

* now uberjar goal prints the name of uberjar file at the end of the process

=== [0.1.6] - 2020-03-01

Added:

* :manifest added to pbuild.edn which allows to add or override default values in MANIFEST.MF

Changed:

* now Created-By field in MANIFEST.MF has a value of pbuilder

=== [0.1.5] - 2020-03-01

Added:

* :excluded-libs added to pbuild.edn for uberjar and standalone mode, that allows exclude libraries from final build.
* :standalone-run-script allows to provide customized run script content when using standalone mode

Fixed:

* in standalone mode, :omit-source? true  is not work. 


=== [0.1.4] - 2020-02-25

Fixed:

* not all changes are pushed to remote origin

Changed:

* now used `git add .` instead of `git add pbuild.edn`

=== [0.1.3] - 2020-02-24

Added:

* badigeon sources in project
* tools.deps version 0.8.677

Fixed:

* call main without parameters
* pbuilder doesn't work without badigeon dependency & tools.deps

=== [0.1.2] - 2020-02-24

Changed:

* bump function: bump from minor to patch by default.

=== [0.1.1] - 2020-02-24

Added:

* bump version functionality

=== [0.1.0] - 2020-02-24

* initial release
